### ISSUE TITLE
BigQuery.Job.query not working

### ISSUE THREAD

**Issue by ranjith965** [companykitchen/big_query#16]
while executing the below query
BigQuery.Job.query("my-project-id",%BigQuery.Types.Query{kind: "bigquery#queryResponse", query: "select * from ranjith"})
am getting the below error
{:error,
%{body: "{\n "error": {\n "errors": [\n {\n "domain": "global",\n "reason": "invalid",\n "message": "Invalid value for: null is not a valid value"\n }\n ],\n "code": 400,\n "message": "Invalid value for: null is not a valid value"\n }\n}\n",
headers: [{"Vary", "X-Origin"},
{"Content-Type", "application/json; charset=UTF-8"},
{"Date", "Thu, 05 Oct 2017 06:30:37 GMT"},
{"Expires", "Thu, 05 Oct 2017 06:30:37 GMT"},
{"Cache-Control", "private, max-age=0"},
{"X-Content-Type-Options", "nosniff"}, {"X-Frame-Options", "SAMEORIGIN"},
{"X-XSS-Protection", "1; mode=block"}, {"Server", "GSE"},
{"Alt-Svc", "quic=":443"; ma=2592000; v="39,38,37,35""},
{"Accept-Ranges", "none"}, {"Vary", "Origin,Accept-Encoding"},
{"Transfer-Encoding", "chunked"}], status_code: 400}}

what does it mean?? How to fix this? please help someone

**Comment by jordan0day** [comment]
It looks like the `parameterMode` parameter needs to either be set or completely removed from the request object. It appears this was a regression introduced by one of the PR's dealing with adding query parameters (or the bigquery API changed to no long support the way we're sending the requests). This is a bit tricky since the parameterMode param isn't supported for "legacy sql" queries, which are the default form.

Additionally, you don't want to set your `type:` field to `bigquery#queryResponse`, as it should be a `bigquery#queryRequest`.

I should have a fix for this up hopefully sometime in the next day or two. For the time being, you can work-around this by creating your query struct like:
`query = %BigQuery.Types.Query{kind: "bigquery#queryRequest", query: "select * from ranjith", useLegacySql: false, parameterMode: "POSITIONAL"}`

**Comment by ranjith965** [comment]
query_string = "SELECT cid, an FROM (SELECT 'client_id' as cid, merchant_id as an, count(ranjith_txn_id) as cnt FROM (TABLE_DATE_RANGE(ranjith, TIMESTAMP('2017-09-01'), TIMESTAMP('2017-09-07'))) where merchant_id is not NULL group by an order by cnt desc)"
BigQuery.Job.query("my-project-id",%BigQuery.Types.Query{useLegacySql: false, kind: "bigquery#queryRequest", parameterMode: "POSITIONAL", query: query_string })

I executed the above query and i got this error.

{:error, %{body: "{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"invalidQuery\",\n    \"message\": \"Syntax error: Expected keyword JOIN but got \\\")\\\" at [1:207]\",\n    \"locationType\": \"other\",\n    \"location\": \"query\"\n   }\n  ],\n  \"code\": 400,\n  \"message\": \"Syntax error: Expected keyword JOIN but got \\\")\\\" at [1:207]\"\n }\n}\n", headers: [{"Vary", "X-Origin"}, {"Content-Type", "application/json; charset=UTF-8"}, {"Date", "Fri, 06 Oct 2017 05:35:20 GMT"}, {"Expires", "Fri, 06 Oct 2017 05:35:20 GMT"}, {"Cache-Control", "private, max-age=0"}, {"X-Content-Type-Options", "nosniff"}, {"X-Frame-Options", "SAMEORIGIN"}, {"X-XSS-Protection", "1; mode=block"}, {"Server", "GSE"}, {"Alt-Svc", "quic=\":443\"; ma=2592000; v=\"39,38,37,35\""}, {"Accept-Ranges", "none"}, {"Vary", "Origin,Accept-Encoding"}, {"Transfer-Encoding", "chunked"}], status_code: 400}}

Even the query syntax is correct, it is showing syntax error..
